### ISSUE TITLE
Organize current effort

### ISSUE THREAD

**Issue by carlosparadis** [erdl/research#1]
We should organize the papers we currently have scattered across discord, e-mails, etc. 

- Create a Google Drive folder for this or use one that already exists, download the papers and put in the folder.
   - Give a consistent file name for each paper, maybe <first author last name word>_<year> (e.g. someone_2014). 
   - Create a Google Sheets, and add the following columns:
      - File name on Drive 
      - Title of the paper (in case we ever lose the file or rename). 
      - Which country (or state) the paper study was done. 
      - Which type of building (residential, office, classroom, etc) 
      - Which type of data (survey, sensor) 
      - The goal of the work concerning thermal tolerance (e.g. propose a new pmv model, propose improvements to the standard, explore participant comfort tolerance, building envelope changes, PV, etc)

Also let me know if there was any other dimension I wrote on the white board in the office.

**Comment by kathrynparadis** [comment]
I used the current Folder: CSBCD HIG205/Publication Drafts/Thermal Comfort

I added a google sheets with the columns mentioned above plus the following columns: 
- Author
- Key Words
- Journal
- Search Source 
- Search Query
- Have Document?

**Comment by kathrynparadis** [comment]
Updated with all of our current papers, moving on to find new literature now.
